Repository atlp-rwanda/e-comm-team-emma25-fe, pull requests merged in 2023-05, with the labels that each got.

#39 Ft wishilist #184749896
  .vs/VSWorkspaceState.json
  .vs/e-comm-team-emma25-fe/v15/.suo
  .vs/slnx.sqlite
  src/components/BottomNav.tsx
  src/components/Chatcomponents/chatmessage.tsx
  src/components/wishlist/wishlistcard.tsx
  src/interfaces/Product.ts
  src/interfaces/functions.ts
  src/views/WishList.tsx
Labels: Ready for review, Awaits another PR

#35 #184749882-delete-a-product
  src/App.tsx
  src/components/DrawerComp.tsx
  src/components/Notification.tsx
  src/views/sellers/AddProduct.tsx
  src/views/sellers/Chatting.tsx
  src/views/sellers/Dashboard.tsx
  src/views/sellers/EditProduct.tsx
  src/views/sellers/Products.tsx
  src/views/sellers/SellerNotification.tsx
Labels: READY, Ready for review

#34 ft - user search product #184749887
  src/utils/AxiosClient.tsx
  src/views/Results.tsx
Labels: READY, Ready for review

#43 feat: checkout function
  src/interfaces/functions.ts
Labels: READY

#41 Ft new user notification #184749891
  src/App.tsx
Labels: READY, Ready for review

#42 Ft user add items to cart #184749892
  src/components/BottomNav.tsx
  src/interfaces/functions.ts
  src/views/Results.tsx
  src/views/RoleUpdate.tsx
Labels: READY

#37 Ft cart view #184749893
  src/App.tsx
  src/components/NavbarTop.tsx
  src/interfaces/Cart.ts
  src/utils/formatCurrency.tsx
  src/views/CartCard.tsx
  src/views/CartView.tsx
  src/views/cart.tsx
  webpack.config.js
Labels: READY, Ready for review

#49 ft-user-admin-seller-view-edit-profile-#184749883
  src/App.tsx
  src/components/NavbarTop.tsx
  src/interfaces/userProfile.ts
  src/views/Login.tsx
  src/views/Profile/editProfile.tsx
  src/views/Profile/userProfile.tsx
  src/views/profile.tsx
  src/views/sellers/Dashboard.tsx
  src/views/sellers/SellerProfile.tsx
Labels: Ready for review

#44 Ft stripe payment #184749898
  src/components/AllProducts.tsx
  src/interfaces/functions.ts
  src/views/CartView.tsx
  src/views/Home.tsx
  src/views/Results.tsx
  src/views/Signup.tsx
  src/views/cart.tsx
Labels: READY

#47 bg-fix-verification
  src/App.tsx
  src/utils/phonHashing.ts
  src/views/Admin/rolePermission.tsx
  src/views/Login.tsx
  src/views/Signup.tsx
  src/views/VerifyCode.tsx
  src/views/sellers/Products.tsx
  webpack.config.js
Labels: READY, Ready for review
