Repository atlp-rwanda/e-comm-team-emma25-fe, pull requests merged in 2023-04, with the labels that each got.

#17 ch-run-code-climate-#184749868
  README.md
Labels: READY

#12 add redux
  package-lock.json
  package.json
  src/App.tsx
Labels: READY

#23 ft-get-user-products, seller dashboard & custom navbar
  src/App.tsx
  src/components/DrawerComp.tsx
  src/interfaces/Product.ts
  src/utils/AxiosClient.tsx
  src/views/sellers/AddProduct.tsx
  src/views/sellers/Dashboard.tsx
  src/views/sellers/Products.tsx
  src/views/sellers/SellerProfile.tsx
Labels: READY

#22 ft-user Signup/Register-#184749873
  src/App.tsx
  src/views/Signup.tsx
Labels: READY

#25 feat: add chat
  package-lock.json
  package.json
  src/App.tsx
  src/assets/styles/chat.css
  src/assets/styles/message.css
  src/components/Chatcomponents/ChatForm.tsx
  src/components/Chatcomponents/Message.tsx
  src/components/Chatcomponents/chatmessage.tsx
  src/utils/AxiosClient.tsx
  src/views/Chat.tsx
  src/views/Login.tsx
  webpack.config.js
Labels: READY, Ready for review

#33 ch-add-system-variable-to-dotenv-webpack
  webpack.config.js
Labels: READY

#29 Ft-notification-panel-#184749890
  src/components/NavbarTop.tsx
  src/components/Notification.tsx
  src/interfaces/Notification.ts
  src/utils/AxiosClient.tsx
  src/views/UserNotifications.tsx
  src/views/sellers/Products.tsx
Labels: Ready for review

#36 Ft logout
  src/assets/styles/chat.css
  src/assets/styles/mobilesearch.css
  src/assets/styles/navbar.css
  src/components/BottomNav.tsx
  src/components/Chatcomponents/chatmessage.tsx
  src/components/NavbarTop.tsx
  src/components/SearchProduct.tsx
  src/components/wishlist/wishlistcard.tsx
  src/utils/AxiosClient.tsx
  src/views/WishList.tsx
Labels: READY, Ready for review
